/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_v1_courses__get"];
        put?: never;
        /** Create Course */
        post: operations["create_course_api_v1_courses__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/join-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Join Info
         * @description Public: course id and name for shareable join links (no JWT).
         */
        get: operations["get_course_join_info_api_v1_courses__course_id__join_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_api_v1_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Course */
        patch: operations["update_course_api_v1_courses__course_id__patch"];
        trace?: never;
    };
    "/api/v1/courses/{course_id}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll In Course */
        post: operations["enroll_in_course_api_v1_courses__course_id__enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Course Students */
        get: operations["list_course_students_api_v1_courses__course_id__students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Student Dashboard
         * @description Get dashboard data for the current student.
         */
        get: operations["get_student_dashboard_api_v1_dashboard_student_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/professor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Professor Dashboard
         * @description Get dashboard data for the current professor.
         */
        get: operations["get_professor_dashboard_api_v1_dashboard_professor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/professor/courses/{course_id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Analytics
         * @description Get detailed analytics for a specific course (roster + concept heatmap).
         */
        get: operations["get_course_analytics_api_v1_dashboard_professor_courses__course_id__analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{quiz_id}/betcha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Place Betcha wager (upfront stake) */
        post: operations["post_quiz_betcha_api_v1_quizzes__quiz_id__betcha_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz-attempts/{attempt_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize attempt Betcha resolution
         * @description Apply PRD §7.7 payout when a wager exists. Pass ``score_percent`` and ``base_coins`` from the quiz scoring step. If no wager was placed, ``betcha_applied`` is false.
         */
        post: operations["post_quiz_attempt_finalize_api_v1_quiz_attempts__attempt_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/concepts/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run LLM concept extraction for a lesson
         * @description Updates the lesson with ``course_id``, ``title``, and ``material_id``. Text is resolved via ``intelligence.ingestion`` (materials row / ``metadata``), then OpenAI extracts concepts; existing concepts for the lesson are replaced.
         */
        post: operations["post_generate_concepts_api_v1_lessons__lesson_id__concepts_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List concepts for a lesson
         * @description Used by professor (Tempo) and student flows (practice / duel) to read stored concepts.
         */
        get: operations["get_lesson_concepts_api_v1_lessons__lesson_id__concepts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * LLM context text for a lesson
         * @description Resolves the lesson to material(s) and returns stored text (materials row / metadata).
         */
        get: operations["get_lesson_context_api_v1_lessons__lesson_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LLM context text for a material */
        get: operations["get_material_context_api_v1_materials__material_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Generate Quiz */
        post: operations["post_generate_quiz_api_v1_quizzes_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{quiz_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quiz */
        get: operations["get_quiz_api_v1_quizzes__quiz_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{question_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Regenerate Question */
        post: operations["post_regenerate_question_api_v1_questions__question_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Question */
        patch: operations["patch_question_api_v1_questions__question_id__patch"];
        trace?: never;
    };
    "/api/v1/questions/{question_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Approve Question */
        post: operations["post_approve_question_api_v1_questions__question_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{quiz_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Publish Quiz */
        post: operations["post_publish_quiz_api_v1_quizzes__quiz_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz-attempts/{attempt_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Score Attempt */
        post: operations["post_score_attempt_api_v1_quiz_attempts__attempt_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lessons */
        get: operations["list_lessons_api_v1_courses__course_id__lessons_get"];
        put?: never;
        /** Create Lesson */
        post: operations["create_lesson_api_v1_courses__course_id__lessons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson */
        get: operations["get_lesson_api_v1_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Lesson */
        patch: operations["update_lesson_api_v1_lessons__lesson_id__patch"];
        trace?: never;
    };
    "/api/v1/courses/{course_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_v1_courses__course_id__materials_get"];
        put?: never;
        /** Upload Material */
        post: operations["upload_material_api_v1_courses__course_id__materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material */
        get: operations["get_material_api_v1_materials__material_id__get"];
        put?: never;
        post?: never;
        /** Delete Material */
        delete: operations["delete_material_api_v1_materials__material_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scoring/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Streak And Coins
         * @description Current user's streak fields and coin balance (PRD dashboard).
         */
        get: operations["get_my_streak_and_coins_api_v1_scoring_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/realtime/protocol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Socket Protocol
         * @description JSON contract for Socket.IO ``/quiz-room`` — use for UI clients and codegen.
         */
        get: operations["get_socket_protocol_api_v1_realtime_protocol_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tempos/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Schedule Tempo */
        post: operations["post_schedule_tempo_api_v1_tempos_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tempos/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upcoming Tempos */
        get: operations["get_upcoming_tempos_api_v1_tempos_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tempos/{quiz_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Tempo Join */
        post: operations["post_tempo_join_api_v1_tempos__quiz_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tempos/{quiz_id}/fire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Dev Fire Tempo
         * @description Dev/demo: emit ``tempo:fire`` immediately.
         */
        post: operations["post_dev_fire_tempo_api_v1_tempos__quiz_id__fire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Create Duel */
        post: operations["post_create_duel_api_v1_duels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duels/{room_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Join Duel */
        post: operations["post_join_duel_api_v1_duels__room_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duels/{room_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Duel Attempt */
        post: operations["post_duel_attempt_api_v1_duels__room_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duels/{room_id}/mark-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Mark Active */
        post: operations["post_mark_active_api_v1_duels__room_id__mark_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duels/{room_id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Settle Duel */
        post: operations["post_settle_duel_api_v1_duels__room_id__settle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shop/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Shop Items
         * @description List all shop items, optionally filtered by category.
         *
         *     Categories: finn_skin, space_item, backdrop, streak_freeze
         */
        get: operations["list_shop_items_api_v1_shop_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shop/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purchase Item
         * @description Purchase a shop item.
         *
         *     Deducts coins from user balance and adds item to inventory.
         *     Returns 402 if insufficient coins, 409 if item already owned (non-consumable).
         */
        post: operations["purchase_item_api_v1_shop_purchase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Inventory
         * @description List all items in the current user's inventory with placement info.
         */
        get: operations["get_inventory_api_v1_me_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Items */
        get: operations["read_items_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerInput */
        AnswerInput: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Selected Choice */
            selected_choice: string;
            /**
             * Time Taken Ms
             * @default 0
             */
            time_taken_ms: number;
        };
        /** AuthResponse */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** Body_upload_material_api_v1_courses__course_id__materials_post */
        Body_upload_material_api_v1_courses__course_id__materials_post: {
            /** File */
            file: string;
        };
        /** ChoiceItem */
        ChoiceItem: {
            /** Key */
            key: string;
            /** Text */
            text: string;
        };
        /**
         * CompletedEvent
         * @description Completed quiz with stats.
         */
        CompletedEvent: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Attempted */
            attempted: number;
            /** Correct */
            correct: number;
            /** Wrong */
            wrong: number;
            /** Concepts */
            concepts: string[];
            /** Coins */
            coins: number;
            /** Betcha */
            betcha: string | null;
        };
        /** ConceptGenerateResponse */
        ConceptGenerateResponse: {
            /** Lesson Id */
            lesson_id: number;
            /** Concepts */
            concepts: components["schemas"]["ConceptItem"][];
            /**
             * Replaced
             * @description Existing concepts for this lesson were replaced
             * @default true
             */
            replaced: boolean;
        };
        /** ConceptItem */
        ConceptItem: {
            /** Id */
            id: number;
            /** Lesson Id */
            lesson_id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ConceptListResponse */
        ConceptListResponse: {
            /** Lesson Id */
            lesson_id: number;
            /** Concepts */
            concepts: components["schemas"]["ConceptItem"][];
        };
        /**
         * ConceptMasteryCell
         * @description Single cell in concept heatmap: student x concept.
         */
        ConceptMasteryCell: {
            /** Student Id */
            student_id: number;
            /** Concept Id */
            concept_id: string;
            /** Concept Name */
            concept_name: string;
            /** Mastery Score */
            mastery_score: number;
        };
        /** ConceptWeight */
        ConceptWeight: {
            /** Concept Id */
            concept_id: number;
            /** Weight */
            weight: number | string;
        };
        /**
         * CourseAnalyticsResponse
         * @description Full course analytics response for professor.
         */
        CourseAnalyticsResponse: {
            /** Course Id */
            course_id: number;
            /** Course Name */
            course_name: string;
            /** Roster */
            roster: components["schemas"]["StudentAnalytics"][];
            /** Concept Heatmap */
            concept_heatmap: components["schemas"]["ConceptMasteryCell"][];
        };
        /**
         * CourseJoinInfo
         * @description Minimal public info for the student join page (no auth).
         */
        CourseJoinInfo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** CourseResponse */
        CourseResponse: {
            /** Id */
            id: number;
            /** Professor Id */
            professor_id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Schedule */
            schedule: {
                [key: string]: unknown;
            };
            /** Join Code */
            join_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CreateCourseRequest */
        CreateCourseRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Schedule */
            schedule?: {
                [key: string]: unknown;
            };
        };
        /** CreateLessonRequest */
        CreateLessonRequest: {
            /** Title */
            title: string;
            /** Week Number */
            week_number: number;
        };
        /** DifficultyWeights */
        DifficultyWeights: {
            /** Easy */
            easy: number | string;
            /** Medium */
            medium: number | string;
            /** Hard */
            hard: number | string;
        };
        /** DuelAttemptResponse */
        DuelAttemptResponse: {
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Room Id */
            room_id: string;
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
        };
        /**
         * DuelCreateBody
         * @description Create a duel lobby for a published quiz (typically ``type=practice``).
         */
        DuelCreateBody: {
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
        };
        /** DuelCreateResponse */
        DuelCreateResponse: {
            /** Room Id */
            room_id: string;
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /** Status */
            status: string;
            /** Realtime */
            realtime?: {
                [key: string]: unknown;
            };
        };
        /** DuelJoinResponse */
        DuelJoinResponse: {
            /** Room Id */
            room_id: string;
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** DuelSettleBody */
        DuelSettleBody: {
            /**
             * Attempt A
             * Format: uuid
             */
            attempt_a: string;
            /**
             * Attempt B
             * Format: uuid
             */
            attempt_b: string;
            /**
             * Opponent Ante
             * @default 0
             */
            opponent_ante: number;
        };
        /** DuelSettleResponse */
        DuelSettleResponse: {
            /**
             * Winner User Id
             * Format: uuid
             */
            winner_user_id: string;
            /**
             * Loser User Id
             * Format: uuid
             */
            loser_user_id: string;
            /** Winner Duel Coins */
            winner_duel_coins: number;
            /** Loser Duel Coins */
            loser_duel_coins: number;
            /**
             * Settled
             * @default true
             */
            settled: boolean;
        };
        /** EnrollRequest */
        EnrollRequest: {
            /** Join Code */
            join_code: string;
        };
        /**
         * FinalizeBetchaBody
         * @description Pre-scored values from the quiz runner; scoring module supplies these at finalize time.
         */
        FinalizeBetchaBody: {
            /** Score Percent */
            score_percent: number | string;
            /**
             * Base Coins
             * @description Pre-Betcha coin pool for this attempt (PRD §7.7)
             */
            base_coins: number;
        };
        /** FinalizeBetchaResponse */
        FinalizeBetchaResponse: {
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Betcha Applied */
            betcha_applied: boolean;
            /** Payout Coins */
            payout_coins?: number;
            /** Effective Factor */
            effective_factor?: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InventoryItemResponse
         * @description An item in the user's inventory.
         */
        InventoryItemResponse: {
            /** Id */
            id: number;
            /** Shop Item Id */
            shop_item_id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Asset Url */
            asset_url: string;
            /** Price Coins */
            price_coins: number;
            /** Rarity */
            rarity: string;
            /**
             * Acquired At
             * Format: date-time
             */
            acquired_at: string;
            /** Placement */
            placement: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * KnowledgeBaseRef
         * @description Optional pointer for chunk ranges; may be empty when using lesson_ids only.
         */
        KnowledgeBaseRef: {
            /** Material Id */
            material_id?: number | null;
            /** Chunk Start */
            chunk_start?: number | null;
            /** Chunk End */
            chunk_end?: number | null;
        };
        /** LessonContextResponse */
        LessonContextResponse: {
            /** Lesson Id */
            lesson_id: number;
            /** Text */
            text: string;
            /**
             * Char Count
             * @description Length of returned text
             */
            char_count: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** LessonResponse */
        LessonResponse: {
            /** Id */
            id: number;
            /** Course Id */
            course_id: number;
            /** Title */
            title: string;
            /** Week Number */
            week_number: number;
            /** Material Id */
            material_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MaterialContextResponse */
        MaterialContextResponse: {
            /** Material Id */
            material_id: number;
            /** Text */
            text: string;
            /** Char Count */
            char_count: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** MaterialResponse */
        MaterialResponse: {
            /** Id */
            id: number;
            /** Course Id */
            course_id: number;
            /** Type */
            type: string;
            /** Filename */
            filename: string;
            /** Processing Status */
            processing_status: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlaceBetchaBody */
        PlaceBetchaBody: {
            /**
             * Attempt Id
             * Format: uuid
             * @description Quiz attempt row to attach the wager to
             */
            attempt_id: string;
            /**
             * Multiplier
             * @enum {string}
             */
            multiplier: "1x" | "3x" | "5x";
            /**
             * Stake Coins
             * @enum {integer}
             */
            stake_coins: 50 | 100 | 200;
        };
        /** PlaceBetchaResponse */
        PlaceBetchaResponse: {
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Multiplier */
            multiplier: string;
            /** Stake Coins */
            stake_coins: number;
            /** Coins Balance After */
            coins_balance_after: number;
        };
        /**
         * ProfessorCourseOverview
         * @description Per-course overview stats for professor dashboard.
         */
        ProfessorCourseOverview: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Enrollment Count */
            enrollment_count: number;
            /** Tempos Scheduled */
            tempos_scheduled: number;
            /** Class Avg Score */
            class_avg_score: number | null;
        };
        /**
         * ProfessorDashboardResponse
         * @description Full professor dashboard response.
         */
        ProfessorDashboardResponse: {
            user: components["schemas"]["ProfessorUserInfo"];
            /** Courses */
            courses: components["schemas"]["ProfessorCourseOverview"][];
        };
        /**
         * ProfessorUserInfo
         * @description User info subset for professor dashboard.
         */
        ProfessorUserInfo: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
        };
        /** PublishResponse */
        PublishResponse: {
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /** Status */
            status: string;
        };
        /**
         * PurchaseRequest
         * @description Request body for purchasing an item.
         */
        PurchaseRequest: {
            /** Item Id */
            item_id: number;
        };
        /**
         * PurchaseResponse
         * @description Response after a successful purchase.
         */
        PurchaseResponse: {
            /** Success */
            success: boolean;
            /** New Balance */
            new_balance: number;
            item: components["schemas"]["ShopItemResponse"];
        };
        /**
         * QuestionEditBody
         * @description Professor edits before approve (PRD review stage).
         */
        QuestionEditBody: {
            /** Text */
            text?: string | null;
            /** Choices */
            choices?: components["schemas"]["ChoiceItem"][] | null;
            /** Correct Choice */
            correct_choice?: string | null;
        };
        /**
         * QuestionRegenerateRequest
         * @description Optional override; otherwise snapshot is loaded from quiz.config.
         */
        QuestionRegenerateRequest: {
            config?: components["schemas"]["QuizGenerationConfig"] | null;
        };
        /**
         * QuizGenerateRequest
         * @description Body for POST /quizzes/generate.
         */
        QuizGenerateRequest: {
            /** Course Id */
            course_id: number;
            config: components["schemas"]["QuizGenerationConfig"];
            /**
             * Quiz Type
             * @default practice
             * @enum {string}
             */
            quiz_type: "tempo" | "practice";
        };
        /** QuizGenerateResponse */
        QuizGenerateResponse: {
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /** Status */
            status: string;
            /** Questions */
            questions: {
                [key: string]: unknown;
            }[];
        };
        /** QuizGenerationConfig */
        QuizGenerationConfig: {
            /** Lesson Ids */
            lesson_ids: number[];
            /** Concepts */
            concepts: components["schemas"]["ConceptWeight"][];
            difficulty_weights: components["schemas"]["DifficultyWeights"];
            /** Num Questions */
            num_questions: number;
            /**
             * Time Per Question
             * @description Seconds per question
             */
            time_per_question: number;
            knowledge_base_ref?: components["schemas"]["KnowledgeBaseRef"] | null;
        };
        /**
         * ScheduleTempoBody
         * @description Set or update fire time for an existing tempo quiz (professor).
         */
        ScheduleTempoBody: {
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /**
             * Scheduled At
             * Format: date-time
             * @description UTC instant when the Tempo should go live.
             */
            scheduled_at: string;
        };
        /**
         * ScoreAttemptInput
         * @description Answers for scoring a completed attempt.
         */
        ScoreAttemptInput: {
            /** Answers */
            answers: components["schemas"]["AnswerInput"][];
        };
        /** ScoreAttemptResult */
        ScoreAttemptResult: {
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Score Pct */
            score_pct: string;
            /** Correct Count */
            correct_count: number;
            /** Total Questions */
            total_questions: number;
            /** Base Coins */
            base_coins: number;
            /** Payout Coins */
            payout_coins?: number | null;
            /** Betcha Effective Factor */
            betcha_effective_factor?: number | null;
            /**
             * Betcha Applied
             * @default false
             */
            betcha_applied: boolean;
            /** Current Streak */
            current_streak?: number | null;
            /**
             * Streak Milestone Bonus Coins
             * @default 0
             */
            streak_milestone_bonus_coins: number;
            /**
             * Streak Already Active Today
             * @default false
             */
            streak_already_active_today: boolean;
        };
        /**
         * ShopItemResponse
         * @description A purchasable item in the shop.
         */
        ShopItemResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Asset Url */
            asset_url: string;
            /** Price Coins */
            price_coins: number;
            /** Rarity */
            rarity: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "student" | "professor";
        };
        /** StreakResponse */
        StreakResponse: {
            /** Current Streak */
            current_streak: number;
            /** Longest Streak */
            longest_streak: number;
            /** Last Activity Date */
            last_activity_date: string | null;
            /** Coins */
            coins: number;
        };
        /**
         * StudentAnalytics
         * @description Per-student analytics for a course.
         */
        StudentAnalytics: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Avatar Config */
            avatar_config: {
                [key: string]: unknown;
            };
            /** Coins */
            coins: number;
            /** Current Streak */
            current_streak: number;
            /** Quizzes Taken */
            quizzes_taken: number;
            /** Avg Score */
            avg_score: number | null;
            /** Last Activity */
            last_activity: string | null;
        };
        /**
         * StudentCourseStats
         * @description Per-course stats for student dashboard.
         */
        StudentCourseStats: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Tests Taken */
            tests_taken: number;
            /** Coins Earned */
            coins_earned: number;
            /** Top Weak Concept */
            top_weak_concept: string | null;
            /** Active Tempo */
            active_tempo: {
                [key: string]: unknown;
            } | null;
            /** Upcoming Events */
            upcoming_events: components["schemas"]["UpcomingEvent"][];
            /** Completed Events */
            completed_events: components["schemas"]["CompletedEvent"][];
        };
        /**
         * StudentDashboardResponse
         * @description Full student dashboard response.
         */
        StudentDashboardResponse: {
            user: components["schemas"]["StudentUserInfo"];
            /** Courses */
            courses: components["schemas"]["StudentCourseStats"][];
        };
        /** StudentResponse */
        StudentResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Avatar Config */
            avatar_config: {
                [key: string]: unknown;
            };
            /** Coins */
            coins: number;
            /** Current Streak */
            current_streak: number;
        };
        /**
         * StudentUserInfo
         * @description User info subset for dashboard.
         */
        StudentUserInfo: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Coins */
            coins: number;
            /** Current Streak */
            current_streak: number;
            /** Avatar Config */
            avatar_config: {
                [key: string]: unknown;
            };
        };
        /** TempoFireResponse */
        TempoFireResponse: {
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /** Fired */
            fired: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** TempoJoinResponse */
        TempoJoinResponse: {
            /**
             * Quiz Id
             * Format: uuid
             */
            quiz_id: string;
            /** Realtime Room Id */
            realtime_room_id: string;
            /**
             * Mode
             * @default tempo
             */
            mode: string;
            /**
             * Hint
             * @default Join Socket.IO namespace /quiz-room with room:join using realtime_room_id.
             */
            hint: string;
        };
        /**
         * UpcomingEvent
         * @description Upcoming quiz/tempo event.
         */
        UpcomingEvent: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Date */
            date: string;
        };
        /** UpdateCourseRequest */
        UpdateCourseRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Schedule */
            schedule?: {
                [key: string]: unknown;
            } | null;
        };
        /** UpdateLessonRequest */
        UpdateLessonRequest: {
            /** Title */
            title?: string | null;
            /** Week Number */
            week_number?: number | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Display Name */
            display_name: string;
            /** Avatar Config */
            avatar_config: {
                [key: string]: unknown;
            };
            /** Coins */
            coins: number;
            /** Current Streak */
            current_streak: number;
            /** Longest Streak */
            longest_streak: number;
            /** Streak Freezes */
            streak_freezes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserUpdateBody */
        UserUpdateBody: {
            /** Display Name */
            display_name?: string | null;
            /** Avatar Config */
            avatar_config?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    patch_me_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_courses_api_v1_courses__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"][];
                };
            };
        };
    };
    create_course_api_v1_courses__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_join_info_api_v1_courses__course_id__join_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseJoinInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_api_v1_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_course_api_v1_courses__course_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCourseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_in_course_api_v1_courses__course_id__enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_course_students_api_v1_courses__course_id__students_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_dashboard_api_v1_dashboard_student_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDashboardResponse"];
                };
            };
        };
    };
    get_professor_dashboard_api_v1_dashboard_professor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfessorDashboardResponse"];
                };
            };
        };
    };
    get_course_analytics_api_v1_dashboard_professor_courses__course_id__analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_quiz_betcha_api_v1_quizzes__quiz_id__betcha_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceBetchaBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceBetchaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_quiz_attempt_finalize_api_v1_quiz_attempts__attempt_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeBetchaBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeBetchaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_generate_concepts_api_v1_lessons__lesson_id__concepts_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_concepts_api_v1_lessons__lesson_id__concepts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_context_api_v1_lessons__lesson_id__context_get: {
        parameters: {
            query?: {
                max_chars?: number;
            };
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_context_api_v1_materials__material_id__context_get: {
        parameters: {
            query?: {
                max_chars?: number;
            };
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_generate_quiz_api_v1_quizzes_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_api_v1_quizzes__quiz_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_regenerate_question_api_v1_questions__question_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["QuestionRegenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_question_api_v1_questions__question_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionEditBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_approve_question_api_v1_questions__question_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_publish_quiz_api_v1_quizzes__quiz_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_score_attempt_api_v1_quiz_attempts__attempt_id__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreAttemptInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreAttemptResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lessons_api_v1_courses__course_id__lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lesson_api_v1_courses__course_id__lessons_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLessonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_api_v1_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lesson_api_v1_lessons__lesson_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLessonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_materials_api_v1_courses__course_id__materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_material_api_v1_courses__course_id__materials_post: {
        parameters: {
            query?: {
                lesson_id?: number | null;
            };
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_material_api_v1_courses__course_id__materials_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_v1_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_material_api_v1_materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_streak_and_coins_api_v1_scoring_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakResponse"];
                };
            };
        };
    };
    get_socket_protocol_api_v1_realtime_protocol_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    post_schedule_tempo_api_v1_tempos_schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleTempoBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upcoming_tempos_api_v1_tempos_upcoming_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    post_tempo_join_api_v1_tempos__quiz_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TempoJoinResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_dev_fire_tempo_api_v1_tempos__quiz_id__fire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TempoFireResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_create_duel_api_v1_duels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuelCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuelCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_join_duel_api_v1_duels__room_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuelJoinResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_duel_attempt_api_v1_duels__room_id__attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuelAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_mark_active_api_v1_duels__room_id__mark_active_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_settle_duel_api_v1_duels__room_id__settle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuelSettleBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuelSettleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shop_items_api_v1_shop_items_get: {
        parameters: {
            query?: {
                /** @description Filter by category */
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purchase_item_api_v1_shop_purchase_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inventory_api_v1_me_inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemResponse"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_items_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
