export const queryKeys = {
  studentDashboard: ['dashboard', 'student'] as const,
  professorDashboard: ['dashboard', 'professor'] as const,
  courseAnalytics: (courseId: number) => ['dashboard', 'professor', 'analytics', courseId] as const,
  scoringMe: ['scoring', 'me'] as const,
  shopCatalog: (category?: string | null) => ['shop', 'items', category ?? 'all'] as const,
  shopInventory: ['shop', 'inventory'] as const,
  spaceLayout: ['space', 'layout', 'default'] as const,
  courses: ['courses'] as const,
  course: (id: number) => ['courses', id] as const,
  courseStudents: (id: number) => ['courses', id, 'students'] as const,
  courseJoinInfo: (id: number) => ['courses', id, 'join-info'] as const,
  courseLessons: (courseId: number) => ['courses', courseId, 'lessons'] as const,
  lesson: (lessonId: number) => ['lessons', lessonId] as const,
  courseMaterials: (courseId: number) => ['courses', courseId, 'materials'] as const,
  lessonConcepts: (lessonId: string) => ['lessons', lessonId, 'concepts'] as const,
  quizDetail: (quizId: string) => ['quizzes', quizId] as const,
  temposUpcoming: ['tempos', 'upcoming'] as const,
  temposJoinable: ['tempos', 'joinable'] as const,
}
